package com.moneymanager.hibernate.pojo;
// Generated Aug 11, 2012 4:29:03 PM by Hibernate Tools 3.4.0.CR1



/**
 * Address generated by hbm2java
 */
public class Address  implements java.io.Serializable {


     private long addressId;
     private String houseno;

    public Address() {
    }

	
    public Address(long addressId) {
        this.addressId = addressId;
    }
    public Address(long addressId, String houseno) {
       this.addressId = addressId;
       this.houseno = houseno;
    }
   
    public long getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(long addressId) {
        this.addressId = addressId;
    }
    public String getHouseno() {
        return this.houseno;
    }
    
    public void setHouseno(String houseno) {
        this.houseno = houseno;
    }




}


