package com.moneymanager.hibernate.pojo;
// Generated Aug 11, 2012 4:29:03 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private int bookId;
     private String isbn;
     private String bookname;
     private Date publishDate;
     private Long price;

    public Book() {
    }

	
    public Book(int bookId) {
        this.bookId = bookId;
    }
    public Book(int bookId, String isbn, String bookname, Date publishDate, Long price) {
       this.bookId = bookId;
       this.isbn = isbn;
       this.bookname = bookname;
       this.publishDate = publishDate;
       this.price = price;
    }
   
    public int getBookId() {
        return this.bookId;
    }
    
    public void setBookId(int bookId) {
        this.bookId = bookId;
    }
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public String getBookname() {
        return this.bookname;
    }
    
    public void setBookname(String bookname) {
        this.bookname = bookname;
    }
    public Date getPublishDate() {
        return this.publishDate;
    }
    
    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }
    public Long getPrice() {
        return this.price;
    }
    
    public void setPrice(Long price) {
        this.price = price;
    }




}


