package com.moneymanager.hibernate.pojo;
// Generated Aug 11, 2012 4:29:03 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Book52 generated by hbm2java
 */
public class Book52  implements java.io.Serializable {


     private long bookId;
     private String isbn;
     private String bookName;
     private Date publishDate;
     private Integer price;

    public Book52() {
    }

	
    public Book52(long bookId, String isbn, String bookName) {
        this.bookId = bookId;
        this.isbn = isbn;
        this.bookName = bookName;
    }
    public Book52(long bookId, String isbn, String bookName, Date publishDate, Integer price) {
       this.bookId = bookId;
       this.isbn = isbn;
       this.bookName = bookName;
       this.publishDate = publishDate;
       this.price = price;
    }
   
    public long getBookId() {
        return this.bookId;
    }
    
    public void setBookId(long bookId) {
        this.bookId = bookId;
    }
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public String getBookName() {
        return this.bookName;
    }
    
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }
    public Date getPublishDate() {
        return this.publishDate;
    }
    
    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }




}


