package com.moneymanager.hibernate.pojo;
// Generated Aug 11, 2012 4:29:03 PM by Hibernate Tools 3.4.0.CR1



/**
 * BookChapter generated by hbm2java
 */
public class BookChapter  implements java.io.Serializable {


     private int bookId;
     private int chapterId;

    public BookChapter() {
    }

    public BookChapter(int bookId, int chapterId) {
       this.bookId = bookId;
       this.chapterId = chapterId;
    }
   
    public int getBookId() {
        return this.bookId;
    }
    
    public void setBookId(int bookId) {
        this.bookId = bookId;
    }
    public int getChapterId() {
        return this.chapterId;
    }
    
    public void setChapterId(int chapterId) {
        this.chapterId = chapterId;
    }




}


