package com.moneymanager.hibernate.pojo;
// Generated Aug 11, 2012 4:29:03 PM by Hibernate Tools 3.4.0.CR1



/**
 * BookPublisher generated by hbm2java
 */
public class BookPublisher  implements java.io.Serializable {


     private long bookId;
     private long publisherId;

    public BookPublisher() {
    }

    public BookPublisher(long bookId, long publisherId) {
       this.bookId = bookId;
       this.publisherId = publisherId;
    }
   
    public long getBookId() {
        return this.bookId;
    }
    
    public void setBookId(long bookId) {
        this.bookId = bookId;
    }
    public long getPublisherId() {
        return this.publisherId;
    }
    
    public void setPublisherId(long publisherId) {
        this.publisherId = publisherId;
    }




}


