package com.moneymanager.hibernate.pojo;
// Generated Aug 11, 2012 4:29:03 PM by Hibernate Tools 3.4.0.CR1



/**
 * Publisher52 generated by hbm2java
 */
public class Publisher52  implements java.io.Serializable {


     private long publisherId;
     private String code;
     private String publisherName;
     private String address;

    public Publisher52() {
    }

	
    public Publisher52(long publisherId, String code, String publisherName) {
        this.publisherId = publisherId;
        this.code = code;
        this.publisherName = publisherName;
    }
    public Publisher52(long publisherId, String code, String publisherName, String address) {
       this.publisherId = publisherId;
       this.code = code;
       this.publisherName = publisherName;
       this.address = address;
    }
   
    public long getPublisherId() {
        return this.publisherId;
    }
    
    public void setPublisherId(long publisherId) {
        this.publisherId = publisherId;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getPublisherName() {
        return this.publisherName;
    }
    
    public void setPublisherName(String publisherName) {
        this.publisherName = publisherName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


